# ====================================================================
# travis.yml: controls ci-server at travis-ci.org
#             build schema2doc and analyse with coverity
#
# @author man-at-home
# ====================================================================

language: java

jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "xZ4sEQOQ47QQOxHV2DXNSxrujanVBicHkOfl30JAjPo40EHHxcXJAzOADRy/lBR2/xV/JLk/nbWkb+++ZKeFsECoDbZX8zFiumvIydvFscWbXoFYuituAscyLPPE5IKYA71I87ldTefeDVQIVbvCC/HuyZ9Bq5gwcW25YdTEEOw1rVaaAFB6ED9++Qg5kUQgZz+bqVQsZYBtiDluVXjowjANu8AYt/eMlWQttSpX5m0454jzeQp/ezyUrUbbuFUZokzzyiMoCQjzFZ5LaVnrkQTUR1P7quGT15vLuVtzuyONwT990EkTzGKVnCDq+zG6eXnrzPFlVLK3l1Bv6oKI1SZomIhJ0T5xNsfeg/uIMPiAw+DvNMKOJ+7wmhlFutqsYlVvX87GtJwis6l7M/k6f6mVx0JTjcl4I0vxcIIMgHPsQJz+SP4IR1LBjro6NL3cpN0jqWlMDrQ9zWvUwn4sk/tesCO+UPehxr2VDd3Z3ztHtl+mwgR5FTXK5xXKgE5hEJ6to62jewcRMyq5UcxA0KR2ge/VLyw1ZSwpn1RYzVQI/bueP5d26o/gV+4uOG9eKlPc1DGrGeuKhwZ0lbbCOY+YInfJOqTYgkPKvV6AivkIcQYOqgtKDm+MKtaDJKOIwHKEfJmQFXWG24N25bp4J5mn/rOvMMKK5GbtfQkXeVQ="

addons:
  coverity_scan:
    project:
      name: "man-at-home/schema2doc"
      description: "db schema doc"
    notification_email: man.from.home@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command:   "./gradlew assemble"
    branch_pattern: master
