-- initial test db flyway migration script
-- ------------------------------------------
-- @author man-at-home

-- tables
-- ------

create table s2d_table1 (
	id bigint generated by default as identity, 
	name varchar(250) not null, 
	primary key (id)
);

COMMENT ON table s2d_table1 is 'some table1 comment';
COMMENT ON column s2d_table1.id is 'PK id comment';
COMMENT ON column s2d_table1.name is 'name comment';

create table s2d_table2 (
	id bigint generated by default as identity, 
	name varchar(250) not null, 
	table1_id bigint not null, 
	primary key (id)
);


COMMENT ON table s2d_table2 is 'a s2d_table2 comment';

create table dummy_user (
	id bigint generated by default as identity, 
	active boolean not null, 
	display_name varchar(250) not null, 
	user_name varchar(50) not null, 
	version bigint not null, 
	primary key (id)
);


-- constraints
-- -----------
alter table dummy_user      add constraint IDX_TT_USER_NAME         unique (user_name);

-- foreign keys
-- ------------
alter table s2d_table2      add constraint FK_s2d_table2 foreign key (table1_id) references s2d_table1;
